#!/usr/bin/env python3
"""Generate the data figures for the Drift-VLA page (v2, two-backbone era).

  B1  static/images/b1_suites.svg              4-suite + avg grouped bars, SmolVLA & Pi0.5
  A3  static/images/a3_latency_breakdown.svg   stacked latency bars (prefix vs expert×K), both backbones
  C1  static/images/c1_capacity_arc.svg        Pi0.5 capacity arc (Drift−FM gap vs adaptation capacity)

Pure stdlib — no matplotlib. Reads figures/data/values.json (v2 schema) as the
single source of truth (mirrors drift-vla-pub/NUMBERS.md).

Style is binding per WEBSITE_DESIGN §5: method colors fixed (Drift #2a78d6, FM
#1baf7a), text never wears a series hue except direct value labels, no dual
axis, hairline grid, light mode only.
"""

import argparse
import json
import math
from pathlib import Path

# ---- §5 palette (validated 2026-07-03, all-pairs CVD PASS) -------------------
BLUE = "#2a78d6"     # Drift (ours)
AQUA = "#1baf7a"     # FM
INK = "#0b0b0b"
INK2 = "#52514e"
MUTED = "#898781"
GRID = "#e1e0d9"
BASELINE = "#c3c2b7"
FONT = "Inter, 'Noto Sans', system-ui, -apple-system, sans-serif"
NUMS = "font-variant-numeric: tabular-nums"

SUITES = [("spatial", "Spatial"), ("object", "Object"), ("goal", "Goal"),
          ("long", "Long"), ("avg", "Avg")]


def load_values(path):
    return json.loads(Path(path).read_text())


def svg_open(w, h):
    return [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" '
            f'font-family="{FONT}">',
            "<!-- generated by make_figures.py — do not hand-edit -->"]


def text(x, y, s, size=13, fill=MUTED, anchor="start", weight=None, style=None):
    a = f'<text x="{x:g}" y="{y:g}" font-size="{size}" fill="{fill}"'
    if anchor != "start":
        a += f' text-anchor="{anchor}"'
    if weight:
        a += f' font-weight="{weight}"'
    if style:
        a += f' style="{style}"'
    return a + f">{s}</text>"


# ---------------------------------------------------------------- B1 ---------
def make_b1(vals, out):
    W, H = 960, 400
    y_lo, y_hi = 50, 100
    top, bottom = 92, 322
    panels = [("smolvla", 40, 452), ("pi05", 532, 944)]
    sy = lambda v: bottom - (bottom - top) * (v - y_lo) / (y_hi - y_lo)

    p = svg_open(W, H)
    # legend
    p.append(f'<rect x="40" y="18" width="12" height="12" rx="3" fill="{AQUA}"/>')
    p.append(text(58, 28, "FM (10-NFE, native)", size=13, fill=INK2))
    p.append(f'<rect x="216" y="18" width="12" height="12" rx="3" fill="{BLUE}"/>')
    p.append(text(234, 28, "Drift (1-NFE, ours)", size=13, fill=INK2))
    p.append(text(944, 28, "LIBERO, 50 ep/task, n=3 eval seeds, native replan cadence",
                  size=12, fill=MUTED, anchor="end"))

    for key, x0, x1 in panels:
        b = vals["backbones"][key]
        # panel title + speedup chip
        p.append(text(x0, 62, b["label"], size=15.5, fill=INK, weight="700"))
        chip = f'Drift decode {b["speedup_vs_fm10"]:g}× faster'
        p.append(text(x1, 62, chip, size=12.5, fill=BLUE, anchor="end", weight="600"))
        # grid + y labels (left panel carries the axis numbers)
        for v in range(y_lo, y_hi + 1, 10):
            gy = sy(v)
            p.append(f'<line x1="{x0}" y1="{gy:g}" x2="{x1}" y2="{gy:g}" stroke="{GRID}" stroke-width="1"/>')
            p.append(text(x0 - 8, gy + 4, str(v), size=12, anchor="end", style=NUMS))
        p.append(f'<line x1="{x0}" y1="{bottom}" x2="{x1}" y2="{bottom}" stroke="{BASELINE}" stroke-width="1"/>')

        slot = (x1 - x0) / len(SUITES)
        bw = 30
        for i, (skey, slabel) in enumerate(SUITES):
            cx = x0 + slot * (i + 0.5)
            if skey == "avg":  # separator before the Avg group
                p.append(f'<line x1="{cx - slot / 2:g}" y1="{top - 6}" x2="{cx - slot / 2:g}" '
                         f'y2="{bottom}" stroke="{BASELINE}" stroke-width="1" stroke-dasharray="3 3"/>')
            for j, (arm, color) in enumerate((("fm", AQUA), ("drift", BLUE))):
                mean, std = b[arm]["suites"][skey]
                bx = cx - bw - 3 if j == 0 else cx + 3
                by = sy(mean)
                p.append(f'<path d="M{bx:g},{bottom} L{bx:g},{by + 3:g} Q{bx:g},{by:g} {bx + 3:g},{by:g} '
                         f'L{bx + bw - 3:g},{by:g} Q{bx + bw:g},{by:g} {bx + bw:g},{by + 3:g} '
                         f'L{bx + bw:g},{bottom} Z" fill="{color}"/>')
                # error bar
                e_up, e_dn = sy(mean + std), sy(mean - std)
                exc = bx + bw / 2
                p.append(f'<line x1="{exc:g}" y1="{e_up:g}" x2="{exc:g}" y2="{e_dn:g}" stroke="{INK2}" stroke-width="1.3"/>')
                # value label
                w = "700" if skey == "avg" else "600"
                p.append(text(exc, e_up - 6, f"{mean:.1f}", size=11.5,
                              fill=INK if skey == "avg" else INK2, anchor="middle",
                              weight=w, style=NUMS))
            lbl_w = "700" if skey == "avg" else None
            p.append(text(cx, bottom + 20, slabel, size=13,
                          fill=INK if skey == "avg" else INK2, anchor="middle", weight=lbl_w))

    p.append(text(W / 2, H - 16, "success rate (%) — FM at its native 10-step decode, Drift at one step",
                  size=13, anchor="middle"))
    p.append("</svg>")
    Path(out).write_text("\n".join(p) + "\n")


# ---------------------------------------------------------------- A3 ---------
def make_a3(vals, out):
    W, H = 960, 490
    x0, x1 = 30, 800
    x_max = 280
    step = 50
    sx = lambda v: x0 + (x1 - x0) * v / x_max

    p = svg_open(W, H)
    p.append(f'<rect x="{x0}" y="14" width="14" height="14" rx="3" fill="{BASELINE}"/>')
    p.append(text(x0 + 21, 26, "VLM prefix (paid once, shared)", size=15, fill=INK2))
    p.append(text(x0 + 276, 26, "·  colored = action expert × NFE", size=15, fill=INK2))

    base_y = H - 58
    grid_top = 44
    for t in range(0, x_max + 1, step):
        gx = sx(t)
        p.append(f'<line x1="{gx:g}" y1="{grid_top}" x2="{gx:g}" y2="{base_y}" stroke="{GRID}" stroke-width="1"/>')
        p.append(text(gx, base_y + 22, str(t), size=14.5, anchor="middle", style=NUMS))
    p.append(f'<line x1="{x0}" y1="{grid_top}" x2="{x0}" y2="{base_y}" stroke="{BASELINE}" stroke-width="1"/>')
    for ms, lbl, dy in ((33.3, "1 step @ 30 Hz (real robot)", 13),
                        (100, "1 step @ 10 Hz (LIBERO)", 31)):
        bx = sx(ms)
        p.append(f'<line x1="{bx:g}" y1="{grid_top}" x2="{bx:g}" y2="{base_y}" stroke="{INK2}" stroke-width="1.2" stroke-dasharray="5 4"/>')
        p.append(text(bx + 6, grid_top + dy, lbl, size=13, fill=INK2, weight="600"))

    y = 96
    bh = 26
    for key in ("smolvla", "pi05"):
        b = vals["backbones"][key]
        p.append(text(x0, y - 6, b["label"], size=16.5, fill=INK, weight="700"))
        y += 14
        rows = [("fm", AQUA, "FM, 10 steps"), ("drift", BLUE, "Drift, 1 step (ours)")]
        for arm, color, label in rows:
            m = b[arm]
            total = m["lat_ms"]
            p.append(f'<circle cx="{x0 + 6}" cy="{y - 9}" r="5" fill="{color}"/>')
            p.append(text(x0 + 17, y - 4, label, size=14.5, fill=INK, weight="600"))
            wp = sx(b["prefix_lat_ms"]) - x0
            p.append(f'<rect x="{x0}" y="{y}" width="{wp - 2:g}" height="{bh}" fill="{BASELINE}"/>')
            ex0, ex1 = x0 + wp, sx(total)
            p.append(f'<path d="M{ex0:g},{y} L{ex1 - 4:g},{y} Q{ex1:g},{y} {ex1:g},{y + 4} '
                     f'L{ex1:g},{y + bh - 4} Q{ex1:g},{y + bh} {ex1 - 4:g},{y + bh} '
                     f'L{ex0:g},{y + bh} Z" fill="{color}"/>')
            note = ""
            if arm == "drift":
                note = (f'<tspan fill="{BLUE}" font-weight="700">  ·  '
                        f'{b["speedup_vs_fm10"]:g}× faster</tspan>')
            p.append(f'<text x="{ex1 + 9:g}" y="{y + bh - 6}" font-size="15" style="{NUMS}">'
                     f'<tspan fill="{INK}" font-weight="700">{total:.0f} ms</tspan>{note}</text>')
            y += 58
        y += 34

    p.append(text((x0 + x1) / 2, base_y + 48,
                  "time to decode one action chunk (ms, A100)", size=15, anchor="middle"))
    p.append("</svg>")
    Path(out).write_text("\n".join(p) + "\n")


# ---------------------------------------------------------------- C1 ---------
def make_c1(vals, out):
    W, H = 960, 440
    left, right, top, bottom = 64, 900, 60, 330
    y_lo, y_hi = 82, 100.5
    pts = [pt for pt in vals["capacity_arc"]["points"] if not pt.get("single_seed")]
    n = len(pts)
    px = lambda i: left + (right - left) * (i + 0.5) / n
    sy = lambda v: bottom - (bottom - top) * (v - y_lo) / (y_hi - y_lo)

    p = svg_open(W, H)
    p.append(f'<circle cx="{left + 6}" cy="22" r="5" fill="{BLUE}"/>')
    p.append(text(left + 16, 26, "Drift (1-NFE)", size=13.5, fill=INK2))
    p.append(f'<circle cx="{left + 136}" cy="22" r="5" fill="{AQUA}"/>')
    p.append(text(left + 146, 26, "FM (10-NFE)", size=13.5, fill=INK2))
    p.append(text(right, 26, "Pi0.5, LIBERO-Spatial — n=3 eval seeds, same LIBERO-adapted VLM", size=12.5,
                  fill=MUTED, anchor="end"))

    for v in range(85, 101, 5):
        gy = sy(v)
        p.append(f'<line x1="{left}" y1="{gy:g}" x2="{right}" y2="{gy:g}" stroke="{GRID}" stroke-width="1"/>')
        p.append(text(left - 10, gy + 4, str(v), size=12.5, anchor="end", style=NUMS))
    p.append(f'<line x1="{left}" y1="{bottom}" x2="{right}" y2="{bottom}" stroke="{BASELINE}" stroke-width="1"/>')

    # connecting lines
    for arm, color in (("drift", BLUE), ("fm", AQUA)):
        d = " ".join(f'{"M" if i == 0 else "L"}{px(i):g},{sy(pt[arm]):g}' for i, pt in enumerate(pts))
        p.append(f'<path d="{d}" fill="none" stroke="{color}" stroke-width="2"/>')

    for i, pt in enumerate(pts):
        cx = px(i)
        gap = pt.get("gap", pt["drift"] - pt["fm"])
        gy_mid = (sy(pt["drift"]) + sy(pt["fm"])) / 2
        # gap connector + label
        p.append(f'<line x1="{cx:g}" y1="{sy(pt["drift"]) + 8:g}" x2="{cx:g}" y2="{sy(pt["fm"]) - 8:g}" '
                 f'stroke="{MUTED}" stroke-width="1" stroke-dasharray="2 3"/>')
        if abs(gap) >= 0.5:
            p.append(text(cx + 10, gy_mid + 4, f"{gap:+.1f}", size=13.5, fill=INK,
                          weight="700", style=NUMS))
        for arm, color in (("drift", BLUE), ("fm", AQUA)):
            cy = sy(pt[arm])
            if pt.get("single_seed"):
                p.append(f'<circle cx="{cx:g}" cy="{cy:g}" r="6.5" fill="#ffffff" stroke="{color}" stroke-width="2.5"/>')
            else:
                p.append(f'<circle cx="{cx:g}" cy="{cy:g}" r="7" fill="{color}" stroke="#ffffff" stroke-width="2"/>')
            dy = -12 if arm == "drift" else 22
            p.append(text(cx, cy + dy, f'{pt[arm]:.1f}', size=12.5,
                          fill=color, anchor="middle", weight="600", style=NUMS))
        p.append(text(cx, bottom + 20, pt["short"], size=12.5, fill=INK2, anchor="middle"))

    p.append(text((left + right) / 2, bottom + 48,
                  "adaptation capacity → (frozen backbone, few steps … full finetune)", size=13, anchor="middle"))
    p.append(text((left + right) / 2, H - 18,
                  "Drift’s edge grows as adaptation capacity shrinks: +11.2 → +5.3 → +2.2",
                  size=13.5, fill=INK, anchor="middle", weight="600"))
    p.append("</svg>")
    Path(out).write_text("\n".join(p) + "\n")


def main():
    here = Path(__file__).resolve().parent
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--data", default=here / "data" / "values.json")
    ap.add_argument("--outdir", default=here.parent / "static" / "images")
    args = ap.parse_args()

    vals = load_values(args.data)
    outdir = Path(args.outdir)
    make_b1(vals, outdir / "b1_suites.svg")
    make_a3(vals, outdir / "a3_latency_breakdown.svg")
    make_c1(vals, outdir / "c1_capacity_arc.svg")
    for f in ("b1_suites.svg", "a3_latency_breakdown.svg", "c1_capacity_arc.svg"):
        print(f"wrote {outdir}/{f}")


if __name__ == "__main__":
    main()
