#!/usr/bin/env python3
"""Generate the data figures for the Drift-VLA page (WEBSITE_DESIGN.md §4/§5).

  A3  static/images/a3_latency_breakdown.svg   stacked latency bar (prefix vs expert×K)
  A5  static/images/a5_success_vs_latency.svg  optional success-vs-latency scatter

Pure stdlib — no matplotlib. Reads figures/data/values.json as the single source
of truth.

Style is binding per §5: method colors fixed (Drift #2a78d6, FM #1baf7a), text
never wears a series hue, direct labels on every mark, no dual axis, hairline
grid, light mode only.
"""

import argparse
import json
import math
import sys
from pathlib import Path

# ---- §5 palette (validated 2026-07-03, all-pairs CVD PASS) -------------------
BLUE = "#2a78d6"     # Drift-VLA (ours)
AQUA = "#1baf7a"     # SmolVLA-FM
INK = "#0b0b0b"
INK2 = "#52514e"
MUTED = "#898781"
GRID = "#e1e0d9"
BASELINE = "#c3c2b7"
FONT = "Inter, 'Noto Sans', system-ui, -apple-system, sans-serif"
NUMS = "font-variant-numeric: tabular-nums"

METHOD_COLOR = {"fm_ns10": AQUA, "fm_ns1": AQUA, "drift": BLUE}
METHOD_ORDER = ["fm_ns10", "fm_ns1", "drift"]

DEMO = {  # preview-only fill-ins for missing values; never publish figures with the tag
    "prefix_lat_ms": 30.9,
    "methods": {
        "fm_ns10": {"expert_lat_ms": 191.7},
        "fm_ns1": {"expert_lat_ms": 19.2},
        "drift": {"expert_lat_ms": 19.7, "sr_mean": 90.2, "sr_std": 1.3},
    },
}


def load_values(path, demo):
    vals = json.loads(Path(path).read_text())
    used_demo = False
    if demo:
        if vals.get("prefix_lat_ms") is None:
            vals["prefix_lat_ms"] = DEMO["prefix_lat_ms"]
            used_demo = True
        for key, m in vals["methods"].items():
            for field, dv in DEMO["methods"][key].items():
                if m.get(field) is None:
                    m[field] = dv
                    used_demo = True
    missing = []
    if vals.get("prefix_lat_ms") is None:
        missing.append("prefix_lat_ms")
    for key, m in vals["methods"].items():
        for field in ("sr_mean", "sr_std", "expert_lat_ms"):
            if m.get(field) is None:
                missing.append(f"methods.{key}.{field}")
    if missing:
        sys.exit(
            "Missing values (fill figures/data/values.json or use --demo for a local preview):\n  "
            + "\n  ".join(missing)
        )
    for m in vals["methods"].values():
        m["total_ms"] = vals["prefix_lat_ms"] + m["expert_lat_ms"]
    return vals, used_demo


def svg_open(w, h):
    return [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" '
        f'font-family="{FONT}">'
    ]


def text(x, y, s, size=13, fill=MUTED, anchor="start", weight=None, style=None):
    a = f'<text x="{x:g}" y="{y:g}" font-size="{size}" fill="{fill}"'
    if anchor != "start":
        a += f' text-anchor="{anchor}"'
    if weight:
        a += f' font-weight="{weight}"'
    if style:
        a += f' style="{style}"'
    return a + f">{s}</text>"


def demo_data_tag(parts, x_right):
    parts.append(
        f'<rect x="{x_right - 318}" y="8" width="318" height="22" rx="6" '
        f'fill="#fff6e0" stroke="#eda100" stroke-dasharray="4 3"/>'
    )
    parts.append(text(x_right - 159, 23, "DEMO PREVIEW DATA — regenerate with measured values",
                      size=11.5, fill="#6b4d00", anchor="middle"))


def nice_step(max_v, target_ticks=6):
    for step in (1, 2, 5, 10, 20, 25, 50, 100, 200):
        if max_v / step <= target_ticks:
            return step
    return 500


# ---------------------------------------------------------------- A3 ---------
def make_a3(vals, demo_used, out):
    W, H = 960, 288
    x0, x1 = 24, 850          # bar span; room right of x1 for total labels
    max_ms = max(m["total_ms"] for m in vals["methods"].values())
    step = nice_step(max_ms * 1.12)
    x_max = step * math.ceil(max_ms * 1.12 / step)
    sx = lambda v: x0 + (x1 - x0) * v / x_max

    p = svg_open(W, H)
    p.append(f"<!-- generated by make_figures.py — do not hand-edit -->")

    # legend: component identity (prefix = neutral; expert wears the method color)
    p.append(f'<rect x="{x0}" y="16" width="12" height="12" rx="3" fill="{BASELINE}"/>')
    p.append(text(x0 + 18, 26, "VLM prefix (shared)", size=13, fill=INK2))
    p.append(text(x0 + 176, 26, "·  colored segment = action expert × NFE", size=13, fill=INK2))
    if demo_used:
        demo_data_tag(p, W - 16)

    grid_top, base_y = 52, 216
    for t in range(0, x_max + 1, step):
        gx = sx(t)
        p.append(f'<line x1="{gx:g}" y1="{grid_top}" x2="{gx:g}" y2="{base_y}" stroke="{GRID}" stroke-width="1"/>')
        p.append(text(gx, base_y + 20, str(t), size=13, anchor="middle", style=NUMS))
    p.append(f'<line x1="{x0}" y1="{grid_top}" x2="{x0}" y2="{base_y}" stroke="{BASELINE}" stroke-width="1"/>')

    bh, y = 22, 72
    for key in METHOD_ORDER:
        m = vals["methods"][key]
        color = METHOD_COLOR[key]
        # row label (chip dot carries method identity; text stays in ink)
        p.append(f'<circle cx="{x0 + 5}" cy="{y - 9}" r="4.5" fill="{color}"/>')
        p.append(text(x0 + 15, y - 5, m["label"], size=13.5, fill=INK, weight="600"))
        # prefix segment (square ends) + 2px surface gap + expert segment (4px rounded data-end)
        wp = sx(vals["prefix_lat_ms"]) - x0
        p.append(f'<rect x="{x0}" y="{y}" width="{wp - 2:g}" height="{bh}" fill="{BASELINE}"/>')
        ex0, ex1 = x0 + wp, sx(m["total_ms"])
        p.append(
            f'<path d="M{ex0:g},{y} L{ex1 - 4:g},{y} Q{ex1:g},{y} {ex1:g},{y + 4} '
            f'L{ex1:g},{y + bh - 4} Q{ex1:g},{y + bh} {ex1 - 4:g},{y + bh} '
            f'L{ex0:g},{y + bh} Z" fill="{color}"/>'
        )
        rate = 1000.0 / m["total_ms"]
        p.append(
            f'<text x="{ex1 + 8:g}" y="{y + bh - 6}" font-size="13.5" style="{NUMS}">'
            f'<tspan fill="{INK}" font-weight="600">{m["total_ms"]:.1f} ms</tspan>'
            f'<tspan fill="{MUTED}"> · ~{rate:.1f} Hz replan</tspan></text>'
        )
        y += 56

    p.append(text((x0 + x1) / 2, base_y + 46,
                  "latency (ms per action chunk)", size=13.5, anchor="middle"))
    p.append("</svg>")
    Path(out).write_text("\n".join(p) + "\n")


# ---------------------------------------------------------------- A5 ---------
# Optional paper/debug figure. The website Results section now uses a compact
# speed/success summary instead of this scatter plot.
def make_a5(vals, demo_used, out):
    W, H = 960, 430
    left, right, top, bottom = 64, 920, 56, 344
    y_lo, y_hi = 70, 95

    lats = [m["total_ms"] for m in vals["methods"].values()]
    lx_lo, lx_hi = math.log10(min(lats) / 2), math.log10(max(lats) * 2)
    sx = lambda v: left + (right - left) * (math.log10(v) - lx_lo) / (lx_hi - lx_lo)
    sy = lambda v: bottom - (bottom - top) * (v - y_lo) / (y_hi - y_lo)

    p = svg_open(W, H)
    p.append(f"<!-- generated by make_figures.py — do not hand-edit -->")

    # legend chip row (identity never rides on color alone: every point is direct-labeled too)
    p.append(f'<circle cx="{left + 6}" cy="22" r="5" fill="{AQUA}"/>')
    p.append(text(left + 16, 26, "SmolVLA-FM", size=13.5, fill=INK2))
    p.append(f'<circle cx="{left + 126}" cy="22" r="5" fill="{BLUE}"/>')
    p.append(text(left + 136, 26, "Drift-VLA (ours)", size=13.5, fill=INK2))
    if demo_used:
        demo_data_tag(p, W - 16)

    # grid + axes
    for v in range(y_lo, y_hi + 1, 5):
        gy = sy(v)
        p.append(f'<line x1="{left}" y1="{gy:g}" x2="{right}" y2="{gy:g}" stroke="{GRID}" stroke-width="1"/>')
        p.append(text(left - 10, gy + 4.5, str(v), size=13, anchor="end", style=NUMS))
    for t in (1, 2, 5, 10, 20, 50, 100, 200, 500):
        if lx_lo <= math.log10(t) <= lx_hi:
            gx = sx(t)
            p.append(f'<line x1="{gx:g}" y1="{top}" x2="{gx:g}" y2="{bottom}" stroke="{GRID}" stroke-width="1"/>')
            p.append(text(gx, bottom + 22, str(t), size=13, anchor="middle", style=NUMS))
    p.append(f'<line x1="{left}" y1="{bottom}" x2="{right}" y2="{bottom}" stroke="{BASELINE}" stroke-width="1"/>')

    p.append(text((left + right) / 2, bottom + 50,
                  "action-generation latency (ms per chunk, log scale)", size=13.5, anchor="middle"))
    p.append(f'<text x="20" y="{(top + bottom) / 2:g}" font-size="13.5" fill="{MUTED}" '
             f'text-anchor="middle" transform="rotate(-90 20 {(top + bottom) / 2:g})">'
             f"LIBERO-Spatial success rate (%)</text>")

    # annotation arrow: FM ns10 -> Drift ("same success, N× faster")
    fm10, dr = vals["methods"]["fm_ns10"], vals["methods"]["drift"]
    speedup = fm10["total_ms"] / dr["total_ms"]
    err_px = lambda m: (m["sr_std"] / (y_hi - y_lo)) * (bottom - top)
    ax0, ay0 = sx(fm10["total_ms"]), sy(fm10["sr_mean"]) - err_px(fm10) - 10
    ax1, ay1 = sx(dr["total_ms"]) + 10, sy(dr["sr_mean"]) - err_px(dr) - 10
    mx, my = (ax0 + ax1) / 2, min(ay0, ay1) - 42
    p.append(
        f'<defs><marker id="ann" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6.5" '
        f'markerHeight="6.5" orient="auto-start-reverse">'
        f'<path d="M0,0 L10,5 L0,10 z" fill="{INK2}"/></marker></defs>'
    )
    p.append(f'<path d="M{ax0 - 4:g},{ay0:g} Q{mx:g},{my:g} {ax1:g},{ay1:g}" '
             f'fill="none" stroke="{INK2}" stroke-width="1.5" marker-end="url(#ann)"/>')
    p.append(text(mx, my - 4, f"FM-level success, {speedup:.1f}× faster",
                  size=13.5, fill=INK, anchor="middle", weight="600"))

    # error bars beneath markers, then markers with a 2px surface ring, then direct labels.
    # Drift and FM-1 share x (both 1 NFE) -> label to the right, separated vertically by
    # their SRs; FM-10 sits far right -> label below it (clamped inside the plot).
    for key in METHOD_ORDER:
        m = vals["methods"][key]
        cx, cy = sx(m["total_ms"]), sy(m["sr_mean"])
        e_up, e_dn = sy(m["sr_mean"] + m["sr_std"]), sy(m["sr_mean"] - m["sr_std"])
        p.append(f'<line x1="{cx:g}" y1="{e_up:g}" x2="{cx:g}" y2="{e_dn:g}" stroke="{MUTED}" stroke-width="1.5"/>')
        for ye in (e_up, e_dn):
            p.append(f'<line x1="{cx - 4:g}" y1="{ye:g}" x2="{cx + 4:g}" y2="{ye:g}" stroke="{MUTED}" stroke-width="1.5"/>')
        p.append(f'<circle cx="{cx:g}" cy="{cy:g}" r="7" fill="{METHOD_COLOR[key]}" stroke="#ffffff" stroke-width="2"/>')
        label = f'{m["label"]} — {m["sr_mean"]:.1f}%'
        if key == "fm_ns10":
            p.append(text(min(cx, right - 140), cy + err_px(m) + 26, label, size=13.5,
                          fill=INK, anchor="middle", weight="600", style=NUMS))
        else:
            p.append(text(cx + 16, cy + 5, label, size=13.5, fill=INK,
                          anchor="start", weight="600", style=NUMS))
    p.append("</svg>")
    Path(out).write_text("\n".join(p) + "\n")


def main():
    here = Path(__file__).resolve().parent
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--data", default=here / "data" / "values.json")
    ap.add_argument("--outdir", default=here.parent / "static" / "images")
    ap.add_argument("--demo", action="store_true",
                    help="fill missing values with preview numbers for local figure layout checks")
    args = ap.parse_args()

    vals, used_demo = load_values(args.data, args.demo)
    outdir = Path(args.outdir)
    make_a3(vals, used_demo, outdir / "a3_latency_breakdown.svg")
    make_a5(vals, used_demo, outdir / "a5_success_vs_latency.svg")
    tag = " [DEMO PREVIEW DATA]" if used_demo else ""
    print(f"wrote {outdir}/a3_latency_breakdown.svg{tag}")
    print(f"wrote {outdir}/a5_success_vs_latency.svg{tag}")


if __name__ == "__main__":
    main()
